version: 2.1
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-28
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
#      - run:
#         name: Chmod permissions #if permission for Gradlew Dependencies fail, use this.
#         command: sudo chmod +x ./gradlew
      - run:
          name: Build applicaiton
          command: ./gradlew assembleDebug
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
#      - run:
#          name: Run Tests
#          command: ./gradlew lint tests
      - run:
          name: Run directory
          command: cd ~/code/app/build/outputs/apk/simpsons/debug && pwd
      - run:
          name: Upload app to seeTest
          command: curl --location --request POST 'https://cloud.seetest.io/api/v1/applications/new' --header 'Cache-Control:no-cache' --header 'Content-Type:multipart/form-data' --header "Authorization:Bearer $token_seeTest" --form 'file=@/home/circleci/code/app/build/outputs/apk/simpsons/debug/app-simpsons-debug.apk' --form 'project=SampleProject'
      - slack/notify:
          color: '#42e2f4'
          mentions: 'prathapk'
          message: This is a custom message notification
          webhook: ${SLACK_WEBHOOK}
orbs:
  slack: circleci/slack@3.4.2
workflows:
  android-workflow:
    jobs:
      - build

